name: Server Pipeline

on:
  push:
    branches: 
      - main
    paths:
      - 'server/**'
jobs:

  build:
    defaults:
      run:
        working-directory: server

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub 
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      uses: docker/build-push-action@v6
      with: 
        context: .
        push: true
        tags: lukaneek/reactjava-server:latest
        secrets: |
          "app_google_apikey=${{secrets.APP_GOOGLE_APIKEY}}"

  deploy:
    needs: build
    runs-on: server 
  
    steps:
    - name: Pull docker image
      run: sudo docker pull lukaneek/reactjava-server:latest
    - name: Delete old docker container
      run: sudo docker rm -f reactjava-server || true
    - name: Run docker container
      run: sudo docker run -d -p 8080:8080 --name reactjava-server lukaneek/reactjava-server